# Generated by Django 6.0.7 on 2026-07-14 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("is_converted", models.BooleanField(default=False, verbose_name="Переведен в активного")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="ads.adcampaign",
                        verbose_name="Рекламная кампания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Потенциальный клиент",
                "verbose_name_plural": "Потенциальные клиенты",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_view_lead", "Может просматривать потенциальных клиентов"),
                    ("can_create_lead", "Может создавать потенциальных клиентов"),
                    ("can_edit_lead", "Может редактировать потенциальных клиентов"),
                    ("can_delete_lead", "Может удалять потенциальных клиентов"),
                    ("can_convert_lead", "Может переводить потенциальных клиентов в активных"),
                ],
            },
        ),
    ]
