# Generated by Django 6.0.7 on 2026-07-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_adcampaign_budget_alter_adcampaign_created_at_and_more"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="first_name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="is_converted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Переведен в активного"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="last_name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(db_index=True, max_length=20, verbose_name="Телефон"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["last_name", "first_name"], name="leads_lead_last_na_e542ff_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["phone"], name="leads_lead_phone_709d42_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["email"], name="leads_lead_email_f663dc_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["campaign", "is_converted"], name="leads_lead_campaig_525763_idx"),
        ),
    ]
