# Generated by Django 6.0.7 on 2026-07-15 11:09

import CRM_system.validators
import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_alter_lead_created_at_alter_lead_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(
                db_index=True,
                max_length=254,
                validators=[django.core.validators.EmailValidator(message="Введите корректный email адрес")],
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="first_name",
            field=models.CharField(
                db_index=True, max_length=100, validators=[CRM_system.validators.validate_full_name], verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="is_converted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Переведен в активного клиента"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="last_name",
            field=models.CharField(
                db_index=True,
                max_length=100,
                validators=[CRM_system.validators.validate_full_name],
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True, max_length=128, region="RU", verbose_name="Телефон"
            ),
        ),
    ]
