[mypy]
python_version = 3.13
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True
exclude = migrations|staticfiles|media|.venv|__pycache__|tests.py
plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = CRM_system.settings

[mypy-phonenumber_field.*]
ignore_errors = True
