# Generated by Django 6.0.7 on 2026-07-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="Название контракта")),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="contracts/", verbose_name="Файл с документом"),
                ),
                ("signing_date", models.DateField(verbose_name="Дата заключения")),
                (
                    "validity_period",
                    models.CharField(
                        help_text="Например: 12 месяцев, 1 год", max_length=100, verbose_name="Период действия"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Сумма контракта")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Контракт",
                "verbose_name_plural": "Контракты",
                "ordering": ["-signing_date"],
                "permissions": [
                    ("can_view_contract", "Может просматривать контракты"),
                    ("can_create_contract", "Может создавать контракты"),
                    ("can_edit_contract", "Может редактировать контракты"),
                    ("can_delete_contract", "Может удалять контракты"),
                ],
            },
        ),
    ]
