# Generated by Django 6.0.7 on 2026-07-14 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        ("leads", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="leads.lead",
                verbose_name="Клиент",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="products.product",
                verbose_name="Услуга",
            ),
        ),
    ]
