# Generated by Django 6.0.7 on 2026-07-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_initial"),
        ("leads", "0002_alter_lead_created_at_alter_lead_email_and_more"),
        ("products", "0002_alter_product_created_at_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="amount",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name="Сумма контракта"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="name",
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name="Название контракта"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="signing_date",
            field=models.DateField(db_index=True, verbose_name="Дата заключения"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["name"], name="contracts_c_name_f85cc1_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["product", "signing_date"], name="contracts_c_product_5991be_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["lead", "signing_date"], name="contracts_c_lead_id_3f38f7_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["signing_date", "amount"], name="contracts_c_signing_5779ee_idx"),
        ),
    ]
