# Generated by Django 6.0.7 on 2026-07-14 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название рекламной кампании",
                        max_length=200,
                        unique=True,
                        verbose_name="Название кампании",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("social", "Социальные сети"),
                            ("context", "Контекстная реклама"),
                            ("email", "Email-рассылка"),
                            ("seo", "SEO"),
                            ("other", "Другое"),
                        ],
                        default="social",
                        max_length=20,
                        verbose_name="Канал продвижения",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Укажите бюджет в рублях",
                        max_digits=10,
                        verbose_name="Бюджет на рекламу",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="products.product",
                        verbose_name="Рекламируемая услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рекламная кампания",
                "verbose_name_plural": "Рекламные кампании",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_view_adcampaign", "Может просматривать рекламные кампании"),
                    ("can_create_adcampaign", "Может создавать рекламные кампании"),
                    ("can_edit_adcampaign", "Может редактировать рекламные кампании"),
                    ("can_delete_adcampaign", "Может удалять рекламные кампании"),
                ],
            },
        ),
    ]
