# Generated by Django 6.0.7 on 2026-07-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
        ("products", "0002_alter_product_created_at_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adcampaign",
            name="budget",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                help_text="Укажите бюджет в рублях",
                max_digits=10,
                verbose_name="Бюджет на рекламу",
            ),
        ),
        migrations.AlterField(
            model_name="adcampaign",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="adcampaign",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="adcampaign",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Введите название рекламной кампании",
                max_length=200,
                unique=True,
                verbose_name="Название кампании",
            ),
        ),
        migrations.AddIndex(
            model_name="adcampaign",
            index=models.Index(fields=["name"], name="ads_adcampa_name_5dc5bd_idx"),
        ),
        migrations.AddIndex(
            model_name="adcampaign",
            index=models.Index(fields=["product", "created_at"], name="ads_adcampa_product_bafa6d_idx"),
        ),
        migrations.AddIndex(
            model_name="adcampaign",
            index=models.Index(fields=["is_active", "created_at"], name="ads_adcampa_is_acti_0295bb_idx"),
        ),
    ]
