# Generated by Django 6.0.7 on 2026-07-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_adcampaign_budget_alter_adcampaign_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adcampaign",
            name="channel",
            field=models.CharField(
                choices=[
                    ("social_vk", "ВКонтакте (VK)"),
                    ("social_tg", "Telegram"),
                    ("social_ok", "Одноклассники"),
                    ("social_fb", "Facebook"),
                    ("social_inst", "Instagram"),
                    ("social_youtube", "YouTube"),
                    ("social_tiktok", "TikTok"),
                    ("social_dzen", "Дзен"),
                    ("seo_yandex", "Яндекс SEO"),
                    ("seo_google", "Google SEO"),
                    ("context_yandex", "Яндекс.Директ"),
                    ("context_google", "Google Ads"),
                    ("email_newsletter", "Email-рассылка"),
                    ("email_autoresponder", "Авто-рассылка"),
                    ("media_banner", "Баннерная реклама"),
                    ("media_video", "Видеореклама"),
                    ("media_native", "Нативная реклама"),
                    ("partner_affiliate", "Партнёрская программа"),
                    ("partner_influencer", "Инфлюенс-маркетинг"),
                    ("offline_radio", "Радио"),
                    ("offline_tv", "Телевидение"),
                    ("offline_print", "Печатная реклама"),
                    ("offline_outdoor", "Наружная реклама"),
                    ("offline_event", "Мероприятия"),
                    ("other", "Другое"),
                ],
                default="social",
                max_length=20,
                verbose_name="Канал продвижения",
            ),
        ),
    ]
