"""
Django settings for CRM_system project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Загружаем переменные из файла .env
load_dotenv()

# Для CI/CD используем .env.test
if os.environ.get('GITHUB_ACTIONS'):
    load_dotenv('.env.test')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Секретный ключ
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Режим отладки
DEBUG = os.getenv("DEBUG", "False") == "True"

# Разрешённые хосты
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition
# Приложения
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # приложения
    "products",  # услуги
    "users",  # пользователи
    "ads",  # рекламные кампании
    "leads",  # потенциальные клиенты
    "contracts",  # контракты
    "customers",  # активные клиенты
    "registration",  # регистрация/авторизация
    "analytics",  # статистика
    # Дополнительные пакеты
    "phonenumber_field",
    "django_cleanup.apps.CleanupConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "CRM_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "CRM_system.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# База данных PostgreSQL
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),  # В Docker будет 'db',
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": 600,  # ← Держать соединение 10 минут
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
# Валидация паролей
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
# Интернационализация
LANGUAGE_CODE = "ru-ru"  # Можно изменить на русский

TIME_ZONE = "Europe/Moscow"  # Московское время

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# Статические файлы
STATIC_URL = "/static/"

# Где Django искать статические файлы
STATICFILES_DIRS = [
    BASE_DIR / "static",  # ← добавляем папку static в корне
]

# Для продакшена (куда собирать все статические файлы)
STATIC_ROOT = BASE_DIR / "staticfiles"

# В продакшене отключить раздачу статики через Django
if not DEBUG:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

# Медиа-файлы (загрузки пользователей)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# URL для редиректа после входа
LOGIN_REDIRECT_URL = "/"  # Перенаправление на главную страницу после входа

# URL для редиректа после выхода
LOGOUT_REDIRECT_URL = "/accounts/login/"  # Перенаправление на страницу входа после выхода

# URL для страницы входа
LOGIN_URL = "/accounts/login/"

# Отключаем кеш для тестов
if "test" in sys.argv:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }

# Настройки для телефонных номеров
PHONENUMBER_DEFAULT_REGION = "RU"  # Россия
PHONENUMBER_DB_FORMAT = "E164"  # Хранить в международном формате
