# Generated by Django 6.0.7 on 2026-07-14 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "contract",
                    models.OneToOneField(
                        help_text="Выберите контракт для клиента",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to="contracts.contract",
                        verbose_name="Контракт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Активный клиент",
                "verbose_name_plural": "Активные клиенты",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_view_customer", "Может просматривать активных клиентов"),
                    ("can_create_customer", "Может создавать активных клиентов"),
                    ("can_edit_customer", "Может редактировать активных клиентов"),
                    ("can_delete_customer", "Может удалять активных клиентов"),
                ],
            },
        ),
    ]
