# Generated by Django 6.0.7 on 2026-07-14 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="lead",
            field=models.OneToOneField(
                help_text="Выберите потенциального клиента для перевода в активные",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="leads.lead",
                verbose_name="Потенциальный клиент",
            ),
        ),
    ]
