# Generated by Django 6.0.7 on 2026-07-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_amount_alter_contract_name_and_more"),
        ("customers", "0002_initial"),
        ("leads", "0002_alter_lead_created_at_alter_lead_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Активен"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["lead"], name="customers_c_lead_id_b8c93f_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["contract"], name="customers_c_contrac_831a49_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["is_active", "created_at"], name="customers_c_is_acti_3160aa_idx"),
        ),
    ]
