# Generated by Django 6.0.7 on 2026-07-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name="Стоимость"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name", "price"], name="products_pr_name_dd5c99_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["created_at"], name="products_pr_created_52f0d7_idx"),
        ),
    ]
